# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jordan Moore
title: Apple IT Professional
email: jordan@jordanrmoore.com
website: jordanrmoore.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: moojomoore
github_username:  moojomoore
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: jordanmoore98
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Jordan. I am the Director of Technology at Loyola Catholic School. I enjoy working with Apple products and solving issues! I have had the opportunity to develop my skills in a wide variety of areas such as customer service, troubleshooting, communication, and project management.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Loyola Catholic School
        link: loyolacatholicschool.org
        # link_text: boringcompany.com
        sub_title: Director of Technology, Former Technology Associate
        caption: June 2015 - Present
        quote: >
          In my time as Director of Technology, I have conceptualized and completed several large-scale projects. This includes communication with many different parties, project management, and significant attention to detail. In the past year, I was able to successfully transition staff and students to distance learning and with the new school year, seamlessly communicate with and support both in-person and distance learners.
        description: | # this will include new lines to allow paragraphs
            - Management of budget, technology staff, projects, and contractors
            - Communication and collaboration with all staff and students, including the use of Incident IQ
            - Deployed and maintained Jamf Pro to secure systems, enforce configurations, and update clients and third-party software for macOS, iOS, and tvOS devices
            - Deployed and managed over 400 macOS, 350 iOS, and 50 tvOS devices for students and staff Preschool-12
            - Successfully migrated CRM system to Salesforce and provided end-user support for all databases

      - layout: left
        title: Moore Solutions
        #link: moore.solutions
        # link_text: boringcompany.com
        sub_title: Owner/Technician
        caption: January 2013 - Present
        quote: >
          At Moore Solutions, I've been able to dive into the client experience. My focus has always been providing the best possible service through communication, ongoing support, and technical knowledge.
        description: | # this will include new lines to allow paragraphs
            - Communicate with clients on a regular basis to ensure everything is running smoothly
            - Schedule times to meet with clients about various business needs
            - Develop, design, and implement websites across multiple businesses
            - Manage and maintain computer networks and computers for multiple businesses including hardware and software repair
            - Provide recommendations on hardware and software based on knowledge of the business
        

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Minnesota State University, Mankato
        caption: 2019
        sub_title: Bachelor of Science - Management Information Systems
        # quote: >
        # description: | # this will include new lines to allow paragraphs
          
  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Jamf 200 - Jamf Certified Technician
        # sub_title: Bachelor of Science - Management Information Systems
        # quote: >
        # description: | # this will include new lines to allow paragraphs       
        
      - layout: top
        title: Jamf 300 - Jamf Certified Admin
        # sub_title: Bachelor of Science - Management Information Systems
        # quote: >
        # description: | # this will include new lines to allow paragraphs       
        
      - layout: top
        title: JumpCloud Core Certification
        # sub_title: Bachelor of Science - Management Information Systems
        # quote: >
        # description: | # this will include new lines to allow paragraphs       
          
  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In my free time, I enjoy
      - 3D Printing
      - House Projects
      - Truck & Tractor Pulling
      

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
